<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <KSPManaged Condition="'$(KSPManaged)' == ''">D:/KSP_Clean/KSP_x64_Data/Managed</KSPManaged>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>8.0</LangVersion>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(KSPManaged)/Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(KSPManaged)/UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(KSPManaged)/UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

<ItemGroup>
    <Compile Include="CSScripts/ModuleTQEngineModeSwitch_v3.cs" />
    <Compile Include="CSScripts/ModuleUnifiedGimbalController.cs" />
    <Compile Include="CSScripts/ModuleWaterfallRemapControllerFix.cs" />
    <Compile Include="ZQ3Stage1Engine.cs" />
    <Compile Include="CSScripts/PusherAnimatedInterstage.cs" />
</ItemGroup>
</Project>
